# -*- mode: ruby -*-
# vi: set ft=ruby :
vm_image = "generic/rocky9"

HOST_IF = "wlp2s0"

DB_NAME = "wordpress"
DB_USER = "wp-user"
DB_PASSWD = "P@ssW0rd"
DB_HOST = "192.168.56.11"

WP_CONFIG_FILE="/var/www/html/wordpress/wp-config.php"
WP_IP = "192.168.56.10"

# 공통 설정 및 리포지터리 업데이트
Common_install_script = <<-SCRIPT
echo "root" | sudo passwd --stdin root
systemctl reload sshd
echo 0. 레포지터리 업데이트...
# time sudo dnf update -y
SCRIPT

####################
# WAS 설치 스크립트 #
####################
WAS_install_script = <<-SCRIPT

echo 1. 패키지 설치
time (
  dnf install httpd php php-mysqlnd mysql-server -y
  systemctl enable --now httpd
  systemctl enable --now mysqld
)
 
echo 2. 방화벽 허용
firewall-cmd --add-service=http --add-service=https --permanent
firewall-cmd --reload

echo 3. Wordpress 소스 코드 설치
time (
wget https://wordpress.org/latest.tar.gz -O wordpress.tar.gz
tar -xvf wordpress.tar.gz -C /var/www/html/
cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
)

echo 4. apache 가상 호스팅 구성
sudo tee -a /etc/httpd/conf.d/wordpress.conf<<EOF
<VirtualHost _default_:80>
    Servername cccr.com
    DocumentRoot /var/www/html/wordpress
    
    <Directory "/var/www/html/wordpress">
        AllowOverride ALL
    </Directory>
</VirtualHost>
EOF
sudo systemctl enable httpd --now


echo 5. 워드프레스 설정 변경
sed -i "s/define( 'DB_NAME', 'database_name_here' );/define( 'DB_NAME', '#{DB_NAME}' );/" "#{WP_CONFIG_FILE}"
sed -i "s/define( 'DB_USER', 'username_here' );/define( 'DB_USER', '#{DB_USER}' );/" "#{WP_CONFIG_FILE}"
sed -i "s/define( 'DB_PASSWORD', 'password_here' );/define( 'DB_PASSWORD', '#{DB_PASSWD}' );/" "#{WP_CONFIG_FILE}"
# sed -i "s/define( 'DB_HOST', 'localhost' );/define( 'DB_HOST', '#{DB_HOST}' );/" "#{WP_CONFIG_FILE}"

systemctl restart httpd

echo 6. PHP to DB SELinux 접근제어 허용
setsebool -P httpd_can_network_connect_db 1

echo 접근제어 설정 확인: `getsebool |grep http_can_network_connect_db`
SCRIPT

####################
# DB 설치 스크립트 #
####################
DB_install_script = <<-SCRIPT

echo 1. 패키지 설치
time (
  dnf install mysql-server -y
  systemctl enable --now mysqld
)
 
echo 2. was 서버의 내부망 IP만 방화벽으로 허용
firewall-cmd --add-rich-rule=\
'rule family=ipv4 source address="#{WP_IP}}/32" \
service name=mysql accept' --permanent

firewall-cmd --reload

echo 방화벽 설정 확인: `firewall-cmd --list-rich-rule`

echo 3. 데이터베이스 서버 구성
sudo mysql -u root<<EOF
CREATE DATABASE IF NOT EXISTS #{DB_NAME};
CREATE USER IF NOT EXISTS '#{DB_USER}'@'#{WP_IP}' IDENTIFIED BY '#{DB_PASSWD}';
GRANT ALL PRIVILEGES ON #{DB_NAME}.* TO '#{DB_USER}'@'#{WP_IP}';
FLUSH PRIVILEGES;
EOF
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "public_network", bridge: "#{HOST_IF}"
  config.vm.network "private_network"
  config.vm.define "wordpress" do |node|
    node.vm.box = vm_image
    node.vm.provider "virtualbox" do |vb|
      vb.name = "wordpress"
      vb.cpus = 2
      vb.memory = 2048
    end

    node.vm.hostname = "wordpress"
    node.vm.provision "shell", inline: Common_install_script
    node.vm.provision "shell", inline: WAS_install_script
  end
end

Vagrant.configure("2") do |config2|
  config2.vm.synced_folder ".", "/vagrant", disabled: true
  config2.vm.network "private_network"
  config2.vm.define "mysql" do |node|
    node.vm.box = vm_image
    node.vm.provider "virtualbox" do |vb|
      vb.name = "mysql"
      vb.cpus = 2
      vb.memory = 2048
    end

    node.vm.hostname = "mysql"
    node.vm.provision "shell", inline: Common_install_script
    node.vm.provision "shell", inline: DB_install_script
  end
end